
name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  linting:
    name: Lint HTML and CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard

      - name: Lint HTML files
        run: |
          htmlhint "src/**/*.html"

      - name: Lint CSS files
        run: |
          stylelint "styles/**/*.css"

  build:
    name: Build Static Website
    runs-on: ubuntu-latest
    needs: linting

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install

      - name: Build static website
        run: |
          npx parcel build src/index.html







